

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    environment:
      XDEBUG_MODE: debug,profile
      XDEBUG_SESSION: docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/html

networks:
  backend:
    driver: bridge
